### ISSUE TITLE
cmake install error

### ISSUE THREAD

**Issue by hmyh1202** [deepomicslab/SpecHap#3]
/usr/include/c++/4.8.2/bits/stl_pair.h:112:26: note:   no known conversion for argument 2 from ‘Fragment’ to ‘const HiCLinker&’
/usr/include/c++/4.8.2/bits/stl_pair.h:108:26: note: constexpr std::pair<_T1, _T2>::pair() [with _T1 = const unsigned int; _T2 = HiCLinker]
       _GLIBCXX_CONSTEXPR pair()
                          ^
/usr/include/c++/4.8.2/bits/stl_pair.h:108:26: note:   candidate expects 0 arguments, 2 provided
make[2]: *** [CMakeFiles/SpecHap.dir/hic_util.cpp.o] Error 1
make[1]: *** [CMakeFiles/SpecHap.dir/all] Error 2
make: *** [all] Error 2

**Comment by panguangze** [comment]
This error caused by "linker.emplace(start_idx, fragment);" in hic_util.h, Seems your GCC version does not support this operation with the explicit constructor. please update your GCC version and try.

**Comment by hmyh1202** [comment]
Fine thank you .
